inputs/docker/client.go, inputs/docker/docker.go
If the docker daemon not started, the docker input should not be started as well (like kubernetes input).
```
2022/06/15 18:07:34 docker.go:181: E! failed to gather docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2022/06/15 18:07:34 reader.go:141: >> count: 33
2022/06/15 18:07:34 reader.go:141: >> count: 14
2022/06/15 18:07:34 reader.go:141: >> count: 1
2022/06/15 18:07:34 reader.go:141: >> count: 5
2022/06/15 18:07:34 reader.go:141: >> count: 34
2022/06/15 18:07:34 reader.go:141: >> count: 11
2022/06/15 18:07:34 reader.go:141: >> count: 10
2022/06/15 18:07:34 reader.go:141: >> count: 13
2022/06/15 18:07:34 reader.go:141: >> count: 8
2022/06/15 18:07:34 reader.go:141: >> count: 11
2022/06/15 18:07:49 docker.go:181: E! failed …
```
=> input: docker should be init failed if the daemon not started

house/house.go
clickhouse table add hostname column
=> clickhouse table add hostname column

inputs/mongodb/dashboard.json
=> fix mongo dashboard import error

inputs/kafka/dashboard-by-topic.json
=> feat: new kafka dashboard by topic dimension

Makefile, conf/input.disk/disk.toml, inputs/mysql/metrics.go, k8s/etcd-dash.json
1. mysql插件添加若干指标的采集
a. long_query_time 指标的采集，表示mysql设置的慢查询的阈值
b. read_only 是否只读，用来判断主从身份
c. max_user_connections 单个用户的最大链接数大小
3. makefile添加 build-linux-arm的命令
4. disk指标的采集ignore_mount_points添加 /var/lib/kubelet/pods，表示不采集k8s pod的mountpath
5. etcd的dashboard支持实例名的变量，采集多个etcd集群的时候可以在一个看板支持
=> feat: serveral changes

inputs/ping/ping.go
当ping不通时，把response时间设置为-1，当大屏显示为延时时可做为特定依据显示成不同颜色和文字，如果不上传数据则不会变化，在大屏显示时不是很友好
=> 在大盘显示时以延时为监控目标时，响应时间在目标ping不通时上传值为-1

inputs/oracle/oracle_linux_amd64.go
fix: oracle plugin bug fix
1、oracle插件实例的metric应该是通用metric加上私有配置的metric，之前版本在实例没有配置私有metric的情况下，没有读取公有metric配置
2、oracle指标重复拉取问题
=> fix: oracle plugin bug fix

inputs/mysql/binlog.go
do not push file number metrics when there is no binlog
=> do not push file number metrics when there is no binlog

inputs/kafka/exporter/exporter.go, inputs/kafka/kafka.go, inputs/mongodb/mongodb.go
1. input.kafka supports kafka_up and kafka_scrape_use_seconds metrics
2. input.mongodb supports mongodb_scrape_use_seconds metric
=> kafka and mongodb add more metrics

agent/agent.go, agent/logs_agent.go, agent/metrics_agent.go, agent/metrics_reader.go, agent/prometheus_agent.go, agent/promethues_agent_none.go, agent/traces_agent.go, config/config.go, main.go, prometheus/prometheus.go
1. 代码重构，统一agent定义，相关数据结构由对应agent自己管理
2. 添加prometheus scrape模块的条件编译，macos上测试不编译promehteus scrape包大小由150MB减少到77MB
=> Feat compile prometheus alternative

agent/metrics_reader.go, api/router_falcon.go, api/router_opentsdb.go, api/router_pushgateway.go, api/router_remotewrite.go, writer/queue.go, writer/writer.go, writer/writers.go
1. 当queue close时，flush还在队列里面的指标
2. queue中管理timeseries，替代原来的types.samples
3. queue、writer、writers的实现解耦；面向对象改造
=> opt: writers code refactor

conf/input.prometheus/prometheus.toml
注释掉 input.prometheus.instances.urls 中的 http://localhost:19000/metrics 脏数据；
否则默认启动categraf后通常会报错： 2022/12/20 14:55:47 prometheus.go:208: E! failed to query url: http://localhost:19000/metrics error: Get "http://localhost:19000/metrics": dial tcp [::1]:19000: connect: connection refused
让运维方产生误解;
=> comment out input.prometheus.instances.urls dirty data

inputs/procstat/procstat.go
1. 进程cpu指标的采集与mem等采集判断统一，添加ins.GatherPerPid的判断
=> fix: procstat cpu metric justify

k8s/deployment-etcd-http.yaml, k8s/deployment.yaml
when categraf is deployed in kubernetes, it's prometheus-agent default use ./data-agent as wal path, which is path of container filesystem(eg.overlayfs). 
usually host volume of container has better i/o performance than container filesystem, so we can config prometheus-agent to use emptyDir volume, which is a temp host volume with pod lifecycle.
=> use volume for prometheus wal

agent/metrics_agent.go, conf/input.netstat/netstat.toml, conf/input.sockstat/sockstat.toml, inputs/netstat/ext_linux.go, inputs/netstat/ext_notlinux.go, inputs/netstat/netstat.go, inputs/sockstat/README.md, inputs/sockstat/sockstat.go, inputs/sockstat/sockstat_linux.go, inputs/sockstat/sockstat_notlinux.go
1. 添加sockstat的插件，读取套接字状态
2. netstat插件添加connectionstats读取的开关，在机器链接数非常高时，可以选择手动关闭指标采集
=> Feat input sockstat

inputs/procstat/procstat.go
```
cat /proc/1778/status
```
```
top -p1778
```
```
categraf --test --inputs procstat
```
rss vms与top对比
=> procstat:push memory info for process

agent/metrics_agent.go
fix: fix panic when reload
1、假设开启了3个插件，启动了程序，3个插件都有实例，运行正常
2、将其中1个插件例如http中的实例删除（配置文件保留），进行reload，此时按照原有逻辑，http这个插件会停止，但是并不会从ma.InputReaders中删除。 此时在reload的start的时候，因为http实例已经删除干净了，所以，不会再次生成 reader 
3、这时候将http这个插件补上一个实例，再次运行reload的时候，因为数组中http还在，所以将会对http这个组件再次执行stop，从而出现 panic: send on closed channel
=> fix: fix panic when reload

agent/metrics_agent.go, agent/metrics_reader.go, config/inline.go, go.mod, inputs/inputs.go
1. 标记instance是否初始化成功
2. gather调用前会判断标记位，没初始化的不调用gather
场景：比如配置只有[[instances]]但是address为空，这样就没办法Init，就不会有一个client，但是gather方法中直接用了client.ping() , 像redis/mysql/oracle 插件。
=> fix instances with nil client

config/config.go
refactor: output log to stdout when use test mode
使用测试模式的时候，强制将日志输出到标准输出，方便测试（否则如果配置了日志，日志将会打印到日志文件，还得另开一个窗口去tail查看）
=> refactor: output log to stdout when use test mode

inputs/xskyapi/xskyapi.go
1. inputs/xskyapi/xskyapi.go:346:64: invalid character U+FF0C '，' in identifier
2. inputs/xskyapi/xskyapi.go:346:74: syntax error: unexpected int in parameter list; possibly missing comma or )
=> xskyapi invalid character fix

inputs/mem/mem.go
针对windows系统的指标输出增加mem_free 指标, 以便和linux处理逻辑保持一致
* 可以解决n9e内置“机器台账表格视图”无法正常显示windows“剩余内存”问题
* 方便配置统一的内存告警规则
=> feature: 针对windows内存增加mem_free指标, 和linux处理逻辑保持一致

agent/metrics_agent.go, conf/input.nsq/nsq.toml, inputs/nsq/nsq.go
目前只增加depth指标，这个最常用，是消息队列的积压指标，指标名称：nsq_channel_depth
=> 增加nsq消息队列采集

inputs/docker/docker.go
input.docker 插件添加 docker_container_health_status 指标，检查 docker 容器健康检查状态。
* 指标为 0 时，healthy
* 指标为 1 时，starting
* 指标为 2 时，unhealthy
=> 添加 docker_container_health_status 容器健康检查状态

inputs/netstat_filter/README.md, inputs/netstat_filter/entry.go, inputs/netstat_filter/netstat_filter.go, inputs/netstat_filter/netstat_tcp.go, inputs/netstat_filter/netstat_tcp_filter.go, inputs/netstat_filter/netstat_tcp_filter_nolinux.go, inputs/netstat_filter/netstat_tcp_nolinux.go
对源IP、源端口、目标IP和目标端口过滤后进行网卡recv-Q、send-Q进行采集，该指标可以很好反应出指定链接的质量，例如rtt时间过长，导致收到服务端ack确认很慢就会使send-Q长期大于0，可以及时通过监控发现，从而提前优化网络或程序。
netstat_filter_tcp_recv_q 的数值表示接收缓冲区中还没拷贝到应用层的数据大小
netstat_filter_tcp_send_q 的数值表示发送缓冲区中未被确认的数据大小
测试样例：
st为2代表TCP_SYN_SENT状态，不进行统计，只统计TCP_ESTABLISHED:1 
扫描结果：
=> 增加统计网络接收队列和发送队列值，多个链接结果加和

inputs/nginx/nginx.go
=> nginx: Add UP metrics

inputs/nginx/nginx.go
slist.PushSamples(prefix string, fields map[string]interface{}, labels ...map[string]string)
推送的时候，已经带上inputName作为prefix参数了，就形成了 nginx_nginx_up的指标名
=> fix nginx: 指标名称重复

inputs/googlecloud/connection.go, inputs/googlecloud/internal/distribution.go
为 googlecloud 中的 distribution 类指标适配分位值指标；当前看只记录了 xxx_sum 的 count 值。
1. 单独记录 mean 意义不大，因为 mean 会拉平 distribution，最好结合 bucket 算 quantiles。
2. 默认算 p50/75/90/95/99/999 quantiles + mean；分位值指标目前以 label 的形式区分。
PS: 当前开发环境暂无gcp账号，需要 categraf maintainers 验证 + review下。
=> fits the quantile value metric for the distribution class metric in googlecloud

conf/input.http_response/http_response.toml, inputs/http_response/http_response.go
添加两个参数：
expect_response_regular_expression：通正则去匹配response body
expect_response_status_codes： 可以通过分隔符，去配置多个response status code.
=> feature: http_response 丰富匹配response的多个配置

inputs/procstat/win_service_windows.go
=> bugfix:  memory leak on windows

inputs/snmp/instances.go
fix: https://github.com/flashcatcloud/categraf/issues/639
=> snmp up synchronize with other oid

types/sample_list.go
fix: PushSamles
To ensure that a variable holds a specific value rather than a pointer value.
Before:
After:
=> fix: PushSamples issue.

conf/input.disk/disk.toml
docs:  disable CDFS by default
发现在windows下，经常可能会有挂载cd驱动器的情况，一般使用率会读取为100%，不知道这是否是实际中一直存在的问题，大佬可以看下，默认禁用CDFS是否是最佳实践
=> docs:  disable CDFS by default

inputs/redis/alerts.json
Fix redis restart alarm detection time is too long
=> Update redis alerts.json

inputs/snmp/table.go
feat: extracting flow values from the rune array
例如某些老机器，如老的深信服AC
获取sfSysTotalMemory 总内存：OID 1.3.6.1.4.1.35047.1.9  会返回 7993.8 MB
增加函数 asciitobytes 将从此字符串中提取数值并转换为字节数
55 57 57 51 46 56 32 77 66   may be the ascii rune arr for string ->  7993.8 MB
=> feat: extracting flow values from the rune array

inputs/mysql/queries.go, inputs/mysql/table_size.go
Add the fragmentation rate of mysql table. This data is because the space cannot be reclaimed by the system after delete, so you need to optimize the table.
=> fragmentation  mysql table

inputs/rocketmq_offset/rocketmq.go
按queue维度聚合，聚合的key 应该为 brokerName + ":" + fmt.Sprint(queueId)
=> fix: [inputs/rocketmq] 修复 msgDiff queue维度聚合逻辑

agent/metrics_agent.go, conf/input.nvidia_smi/nvidia_smi.toml, inputs/nvidia_smi/builder.go, inputs/nvidia_smi/nvidia_smi.go, inputs/nvidia_smi/scrape.go
=> feat: support nvidia-smi timeout

.github/workflows/ci.yml
优化ci流程，解决一个ci报错就不跑其他ci的问题。并且可以同时跑所有的ci，节约时间。
=> ci: update ci workflows

inputs/net/net.go
/sys/class/net/<iface>/speed 返回error或者负值时，整个interface的指标都被丢起了
=> fix: metrics lost when net interface has invalid speed

inputs/oracle/oracle.go
feat: Compatible oracle TNS connection string
1、去除panic
2、兼容tns模式和 ip:port/servicename 模式
类似如下连接串也是常用的，特别是在集群模式中：
address = "(DESCRIPTION =    (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))    (CONNECT_DATA =      (SERVER = DEDICATED)      (SERVICE_NAME = orcl)    )  )"
=> feat: compatible oracle tns connection string

api/router_func.go, api/router_pushgateway.go, api/server.go
- support standard [pushgateway http api](https://github.com/prometheus/pushgateway/tree/v1.8.0#api) on write. 
> POST PUT    /api/push/pushgateway/metrics/job/<JOB_NAME>{/<LABEL_NAME>/<LABEL_VALUE>}
- add snappy compress on pushgateway.
=> feat: pushgateway api support url labels

inputs/prometheus/consul.go, inputs/prometheus/prometheus.go
=> feat: prometheus consul service auto discovery

conf/config.toml, config/config.go, config/hostname.go
配置文件支持使用sn变量来表示Bios Serial Number。可用于主机名和全局变量。
=> Support Vars $sn for Config

heartbeat/platform/platform_common.go
Check getPythonVersion Result Empty to Fix [window下程序异常退出](https://github.com/flashcatcloud/categraf/issues/928#issue-2294304761)
=> fix: Check getPythonVersion Result Empty

LICENSE
Hi,
I am one of the Telegraf maintainers. It is really exciting to see that you been able to re-use much of Telegraf in this project! 
As this project is a fork of many of the Telegraf code base, it is important to maintain the copyright notice and the license itself. That way you stay compliant with the MIT license which requests:
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
This PR re-adds the InfluxData copyright notice to the existing license.
Thanks!
=> chore: Readd InfluxData to the copyright line of license

conf/input.disk/disk.toml
If not ignored, it will cause categraf to request a large amount of memory when starting up, leading to an OOM (Out Of Memory) error.
what is juicefs ? click https://juicefs.com/
=> add: input.disk ignore JuiceFS by default

conf/input.disk/disk.toml
Sorry, I got the wrong file type in the previous PR.
Please let me fix it, thanks.I've tested it, it must be right this time.
```
#df -hT
JuiceFS:juicenas fuse.juicefs  1.0P   12T 1013T   2% /mnt/juicenas
```
```
metrics:
{device="JuiceFS:juicenas",fstype="fuse.juicefs",ident="juice-nas",mode="rw",path="/mnt/juicenas"}
```
=> fix: input.disk juicefs type

conf/input.procstat/procstat.toml, inputs/procstat/procstat.go
功能描述
- 对单进程的指标，使用正则表达式，从 cmdline 中提取字串作为 label 标签。
使用场景
- 需要对大量相同进程使用 procstat 抓取基础指标时，仅靠pid难以区分进程的功能，静态标签无法适应频繁启停。
使用案例
启动命令行模板: `java -cp lib/* -Denv=${tenantry} main.GwStartup --serviceName=${service} --serverId=${serverId}`
配置案例: 静态标签 [region, product]，采集每个进程，不统计总量，开启所需指标，使用正则动态获取
```
[[instances]]
search_cmdline_substring = "main.GwStartup"
labels = { region="us-west-1", product="gw" }
gather_total = false
gather_per_pid = true
gather_more_metrics = ["threads", "io", "uptime", "cpu", "mem", "jvm"]
labels_from_cmdline_reggroup = "-Denv=(?P<vfenv>[\\w]+)\\s+main.GwStartup\\s+--serviceName=(?P<serviceName>[\\w]+)\\s+--serverId=(?P<serverId>\\d{1,4})"
```
=> feat: plugin procstat - extract label from cmdline using regexp Named capturing group

agent/metrics_agent.go, conf/input.ethtool/ethtool.toml, go.mod, inputs/ethtool/README.md, inputs/ethtool/command_linux.go, inputs/ethtool/ethtool_linux.go, inputs/ethtool/ethtool_notlinux.go, inputs/ethtool/namespace_linux.go
=> feat: add ethtool plugin

inputs/ipmi/exporter/collector_bmc.go, inputs/ipmi/exporter/collector_bmc_watchdog.go, inputs/ipmi/exporter/collector_chassis.go, inputs/ipmi/exporter/collector_dcmi.go, inputs/ipmi/exporter/collector_ipmi.go, inputs/ipmi/exporter/collector_notwindows.go, inputs/ipmi/exporter/collector_sel.go, inputs/ipmi/exporter/collector_sm_lan_mode.go, inputs/ipmi/exporter/collector_windows.go, inputs/ipmi/exporter/config.go, inputs/ipmi/exporter/freeipmi/freeipmi.go, inputs/ipmi/instances.go
=> refactor: reduce ipmi log

inputs/procstat/procstat.go
补充了缺少的属性
fix https://github.com/flashcatcloud/categraf/pull/951
=> fix: plugin procstat - labels_from_cmdline_reggroup support mem* metrics

config/logs/source.go, logs/input/file/tailer.go, logs/input/kubernetes/launcher.go, logs/util/kubernetes/kubelet/kubelet_client.go
Fix 在containerd日志格式下，错误日志匹配。以及query 日志太多
=> line_parser.go:158: cannot parse docker message, invalid JSON: 

logs/input/kubernetes/launcher.go
我们在调查问题的时候，比如哪个pod 访问我的应用的时候需要知道ip。因为访问记录都是记录ip地址。IP查询最直接。
=> add pod ip in the log tags

inputs/zookeeper/zookeeper.go
不算是bug，但沿着interval不打开注释默认15的习惯，我的zk配置也没有打开注释，导致排查了一天😂
所以加个默认值，规避此类情况。
=> chore: 🍻 增加zk插件timeout配置项的默认值

conf/input.clickhouse/clickhouse.toml, conf/input.consul/consul.toml, conf/input.docker/docker.toml, conf/input.influxdb/influxdb.toml, inputs/clickhouse/README.md, inputs/conntrack/README.md, inputs/docker/README.md, inputs/filecount/README.md, inputs/influxdb/README.md, inputs/ipvs/README.md, inputs/kafka/README.md, inputs/kubernetes/README.md, inputs/mongodb/README.md, inputs/nginx/README.md, inputs/prometheus/README.md, inputs/rabbitmq/README.md, inputs/sqlserver/README.md
修复一些不够严谨的情况：
- 一些地方是没有链接。
- 一些地方格式有误。
- 一些配置文件有误。
=> typo: 修复一些链接或文档的错漏

conf/input.influxdb/influxdb.toml
[influxdb监控有一个默认的配置地址，正常安装后会有一个请求不通的网络地址，修改为默认关闭，并将地址修改为localhost]
=> style[更改默认配置]: 修改influxdb监控的默认配置

ibex/cmd_nix.go, ibex/cmd_windows.go, ibex/task.go
Windows cmd 需要使用  ANSI 编码 + CRLF 换行的脚本。
- 使用 Windows API 转换 ANSI，而不是 golang.org/x/text/encoding 转换，确保最大兼容性，结果一定与机器匹配。
fix https://github.com/flashcatcloud/categraf/issues/1018
=> fix: ibex-windows cmd not support i18n charset

config/config.go
get the error sn when there is some warning like redhat os
like this
=> fix: get the error sn when there is some warning like redhat os

agent/update/update_windows.go
旧文件更名为 {name}.old
若权限允许，设置重启后删除旧版本。当然不删也不会有什么影响。
NOTE: 无法在 IDE debug 下测试
=> feat: windows agent update

logs/sender/batch_strategy.go
增加触发限流的标识
如果缓存允许最大并发批次是1k，如下
但是实际处理过程中，如果有发现超过1k的并发，那么应该有标识，标识输出的内容是：“buffer full”
同时可以配合mtail发现关键字，进一步针对指标配置阈值、告警，一气呵成
需要注意的一点是：
如果采集的内容达到一次发送的上限，也会直接发送走，不会触发该标识。所以需要合理定义batch_max_size、batch_max_content_size大小
=> chore: Add rate limiting log

heartbeat/filesystem/filesystem_linux.go
fix bug if the disk name is too long to display
for example:
=> fix: df use the POSIX output format

inputs/redis_sentinel/redis_sentinel.go
这里的tag修改的都是client.tags这个map，每一次修改都会更新同名标签，并且导致tag累积，后面的指标被添加了很多无关的标签
=> fix: 修复redis_sentinel标签异常

inputs/aliyun/cloud.go
阿里云 list的metrics ，返回只有metric name 和 namespace，没有dimensions信息。 isSelected需要去除dimensions的比较。
=> fix: dimensions for aliyun

conf/input.http_response/http_response.toml, go.mod, go.sum, inputs/http_response/http_response.go
https://github.com/flashcatcloud/categraf/issues/659
=> add-http_response 添加trace数据

inputs/procstat/procstat.go
In some cases, search_string is too complex and you don't want to include it in the metrics. Choose not to include the search string and use custom labels to identify the metrics.
=> chore: add procstat input ExcludeSearchString option

conf/input.oracle/metric.toml, conf/input.oracle/oracle.toml
修复配置文件错误，原来的配置文件会导致 oracle 无法加载：
1. W! no instances for input:oracle
2. E! failed to load configuration of plugin: local.oracle error: toml: line 140 (last key "metrics.request"): unexpected EOF; expected "'''"
=> fix(oracle): configuration file errors

conf/input.elasticsearch/elasticsearch.toml
```num_most_recent_indices```是telegraf的es插件配置，当前插件es exporter ， 没有这个配置项，先删除。
=> chore(es): Remove the legacy configuration item num_most_recent_indices

inputs/elasticsearch/collector/ilm_indices.go, inputs/elasticsearch/collector/ilm_indices_test.go, inputs/elasticsearch/collector/indices.go, inputs/elasticsearch/collector/indices_mappings.go, inputs/elasticsearch/collector/indices_mappings_test.go, inputs/elasticsearch/collector/indices_settings.go, inputs/elasticsearch/collector/indices_settings_test.go, inputs/elasticsearch/collector/indices_test.go, inputs/elasticsearch/elasticsearch.go
1、elasticsearch插件增加num_most_recent_indices参数处理逻辑
2、补充elasticsearch插件ilm_indices、indices_settings、indices_mappings、indices_aliases 参数indices_include生效逻辑以及参数num_most_recent_indices处理逻辑
=> 补充elasticsearch插件num_most_recent_indices参数逻辑&完善indices_include生效范围

heartbeat/network/network_windows.go
The "network" field in the heartbeat reported data is null in a Windows 10 environment.
=> fix: The "network" field in the heartbeat reported data is null in a Windows 10 environment.

inputs/ipmi/exporter/freeipmi/freeipmi.go
**- 问题：**
如果系统没有安装 freeipmi 相关命令，categraf 日志会持续报错 “executable file not found in $PATH”，同时进程线程数会不断增长，未被释放。
**- 原因：**
每次调用 Execute 时，都会调用 freeipmiConfigPipe 创建一个 goroutine，用于向 named pipe（FIFO 文件）写入 config 数据。
如果 freeipmi 相关命令不存在，exec.Command(cmd, args...).CombinedOutput() 会立即失败，不会读取 named pipe。
此时 goroutine 在尝试打开 named pipe (os.OpenFile) 时会阻塞，因为 FIFO 的写端没有被读端打开，OpenFile 无法返回。
由于外部命令没有启动（或启动失败），FIFO 的读端永远不会打开，写端的 goroutine 永远不会退出，导致线程/协程泄漏。
后续的逻辑：
```
defer func() {
if err := os.Remove(pipe); err != nil {
log.Println("msg", "Error deleting named pipe", "error", err)
}
}()
```
即使 pipe 文件被删除，openFile 阻塞的 goroutine 也不会收到通知退出，还是会卡着。
**- 解决：**
在创建 pipe 和写 goroutine 前，先检查命令是否存在，避免无意义的 goroutine 启动。
```
if _, err := exec.LookPath(cmd); err != nil {
return Result{nil, fmt.Errorf("executable %s not …
```
=> Fix: The issue of goroutine leakage when freeipmi is not installed
