agent/agent.go
It's better to understand the magic number "6".
=> agent: use const for input file prefix

conf/input.oracle/metric.toml
feat: add some metric for oracle
锁数量情况、慢查询p95 p99情况
=> feat: add some metric for oracle

api/server.go, conf/config.toml, config/config.go, config/logs/integration_config.go, k8s/README.md
1.  fix httpserver panic
2. print config parsing error 
3. fix config key of log processing rules
=> fix httpserver panic

inputs/mysql/dashboard-by-aws-rds.json
1. 使用telegraf采集aws rds 数据并输出到Prometheus
```
[[outputs.prometheus_client]]
listen = ":9273"
```
2. 使用 categraf 的 input.prometheus 获取 telegraf 数据
=> 增加 aws cloudwatch rds 大盘，该大盘需要配合telegraf使用

config/logs/integration_config.go, logs/input/file/tailer.go, logs/parser/parser.go
see details:
https://en.wikipedia.org/wiki/GB_2312
https://en.wikipedia.org/wiki/GBK_(character_encoding)
https://en.wikipedia.org/wiki/GB_18030
https://en.wikipedia.org/wiki/Big5
=> support log decoding Chinese characters

agent/agent.go, conf/input.snmp/snmp.toml, go.mod, go.sum, inputs/snmp/README.md, inputs/snmp/netsnmp.go, inputs/snmp/snmp.go, inputs/snmp/wrapper.go
=> snmp plugin

inputs/oracle/oracle_linux_amd64.go
fix: oracle plugin bug fix
----不应重复添加
=> fix: oracle plugin bug fix

inputs/system/alerts-linux.json
add load and inode alerts for linux
=> add load and inode alerts for linux

inputs/rabbitmq/dashboard-3.8-.json
dashboard for rabbitmq version 3.8-
=> dashboard for rabbitmq 3.8-

logs/input/file/tailer.go, logs/input/kubernetes/json_parser.go
=> change pod parser to jsonparser

inputs/tomcat/README.md
=> update tomcat docs

inputs/mtail/mtail.go
=> mtail: emaitl prog label

agent/agent.go, agent/metrics_agent.go, agent/metrics_reader.go, inputs/provider.go
http provider获取到的配置变化时，由全局reload改为reload有变化的inputs
```shell
➜  categraf git:(main) ✗ ./categraf --test --inputs mysql --configs /Users/bevin/Documents/github/categraf/conf_local
2022/11/25 15:25:28 main.go:110: I! runner.binarydir: /Users/bevin/Documents/github/categraf
2022/11/25 15:25:28 main.go:111: I! runner.hostname: xiaozhengdeMacBook-Pro.local
2022/11/25 15:25:28 main.go:112: I! runner.fd_limits: (soft=61440, hard=unlimited)
2022/11/25 15:25:28 main.go:113: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2022/11/25 15:25:28 config.go:33: I! tracing disabled
2022/11/25 15:25:28 provider.go:69: I! use input provider: [http]
2022/11/25 15:25:28 agent.go:98: I! agent starting
2022/11/25 15:25:28 provider.go:396: I! http provider: start reload config from remote: …
```
=> feat: support single input reload

conf/config.toml, config/config.go, ibex/client/cli.go, ibex/cmd_nix.go, ibex/cmd_windows.go, ibex/heartbeat.go, ibex/task.go, ibex/tasks.go, ibex/types/types.go
添加告警自愈agent功能到categraf（原ibex agent）
=> add ibex agent

agent/traces_agent.go, agent/traces_agent_none.go, config/traces/components.go, config/traces/config.go, config/traces/config_none.go, house/types.go, traces/collector.go, traces/host.go, traces/service.go, traces/settings.go
1. traces条件编译，包体积减少17M
2. 移除house types中定义的Sample
=> feat: compile traces alternative

ibex/cmd_windows.go, ibex/task.go
=> Repair the windows ibex agent

.gitignore, agent/metrics_reader.go, api/router_pushgateway.go, inputs/kafka/alerts.json, writer/writers.go
1. 批量写入safeList避免重复加锁
2. 优化input.kafka堆积告警，避免同topic/同consumegroup堆积时多partition重复告警
=> feat:batch write samples

api/router_falcon.go, api/router_opentsdb.go, api/router_pushgateway.go, api/router_remotewrite.go, api/server.go, ibex/client/cli.go, inputs/collector.go, inputs/exec/exec.go, inputs/provider.go, main_posix.go, main_windows.go, parser/prometheus/parser.go, types/sample.go, writer/writer.go
=> opt: code refactor

Makefile, README.md, types/safe_list.go, writer/writers.go
1. 修复writer的空指针错误
2. safelist代码优化
3. Makefile新增max下arm的构建命令，添加mac下pack文档
=> fix: writer nil pointer err

inputs/mtail/mtail.go
label lost in mtail plugin, now fix it
=> fix label lost in mtail plugin

inputs/mongodb/dashboard.json
**What type of PR is this?**
update mongo dashboard template
**What this PR does / why we need it**:
Each chart in the dashboard contains the metric data of all instances. After updating, you can select the instance
**Which issue(s) this PR fixes**:
Fixes #
https://github.com/flashcatcloud/categraf/issues/255
**Special notes for your reviewer**:
=> update: view metrics data by instance

inputs/procstat/procstat.go
1. 修复计算proc uptime把启动时间当成uptime的问题
=> fix: procstat uptime calculation

agent/metrics_agent.go, conf/input.systemd/systemd.toml, go.mod, go.sum, inputs/systemd/README.md, inputs/systemd/systemd_linux.go
systemd unit /service /tasks metrics collector
=> add systemd plugin

inputs/procstat/native_finder.go, inputs/procstat/native_finder_notwindows.go, inputs/procstat/native_finder_windows.go, inputs/procstat/process.go, inputs/procstat/procstat.go
feat: procstat support specify user
=> feat: procstat support specify user

inputs/procstat/native_finder_windows.go
=> fix: fix procstat for windows

conf/config.toml, config/config.go, main.go, main_posix.go
log with lumberjack, detail issue : #322
=> log with lumberjack

inputs/procstat/procstat.go
对于一份配置，采集多个process的使用场景：
label中pid不太直观，增加一个comm的label，对于非java类的进程会更直观一些
=> add comm as tag for procstat

inputs/aliyun/README.md
=> feat: add aliyun redis kvstore_standard dashboard

inputs/redis/dashboard_for_redis6.2.x_exporter1.43.x.json
dashboard for k8s redis exporter
=> feat: add dashboard for redis-exporter

inputs/switch_legacy/dashboard.json, inputs/vsphere/dashboards.json
=> add dashboards for vsphere and switch_legacy

inputs/aliyun/dashboard_for_redis_kvstore_standard.json
增加 redis dashboard，适用于 aliyun kvstore 标准 redis 组件
=> feat: add redis dashboard for aliyun kvstore standard

logs/util/kubernetes/kubelet/kubelet.go
autodiscovery filter is not used here
=> delete code wich is not used for log autodiscovery filter

inputs/exec/scripts/ssh/collect_ssh_conn_count.sh
fix: exec script data format error
=> fix: exec script data format error

inputs/mtail/internal/exporter/export_test.go, inputs/mtail/internal/exporter/graphite_test.go, inputs/mtail/internal/exporter/json.go
=> fix: fix test error

conf/input.mysql/mysql.toml, inputs/mysql/README.md, inputs/mysql/mysql.go
#463 #464 解决address 参数对  mysql 用户为 localhost 值的支持
=> mysql plusgin  address support unix

inputs/oracle/oracle_linux_amd64.go
fix: fix reload panic when instance is empty
=> fix: fix reload panic when instance is empty

conf/input.consul/consul.toml, go.mod, go.sum, inputs/consul/README.md, inputs/consul/consul.go
I added more metrics for consul plugin.
=> add consul metrics

inputs/exec/exec.go
fix: return error msg when exec error
=> fix: return error msg when exec error

agent/metrics_agent.go, inputs/provider_manager.go
抽象程度还不够，后面再优化。 anyway， it works
=> fix http_provider

agent/metrics_reader.go, conf/config.toml, config/config.go, go.mod
1. add input runtime concurrency
=> Feature add input runtime concurrency

writer/writers.go
=> do not copy lock for snapshot of writers 

inputs/ipvs/ipvs_linux_amd64.go
修复ipvs plugin Gather方法
之前这个方法就没实现SampleGatherer 接口, 多了个返回error
=> fix ipvs gather bug

inputs/aliyun/cloud.go, inputs/aliyun/internal/manager/cms.go
[阿里云插件采集报错](https://github.com/flashcatcloud/categraf/issues/600) 修复json格式化异常，aliyun metric filter支持正则。
=> aliyun metric  支持正则

conf/input.nginx/nginx.toml, inputs/nginx/nginx.go
fix: target 请求超时也输出nginx_up指标
feature: nginx supports adding extra tags in batches.
=> feature: nginx supports adding extra tags in batches.

inputs/whois/whois.go
fix: fix whois for cn domain
cn域名不一定返回updatetime
Close #684
=> fix: fix whois for cn domain

main_windows.go
=> refactor: app log for windows

inputs/aliyun/internal/manager/cms.go
fix cloudMonitor metrics label miss
=> fix cloudMonitor metrics label miss

api/router_falcon.go, api/router_opentsdb.go, api/router_pushgateway.go, api/router_remotewrite.go, conf/config.toml, config/config.go
fixbug, resolve ignore hostname not effective in `api`
=> fixbug, ignore hostname not effective, use `OmitHostname`

agent/install/service_linux.go
allow ExecReload in systemd service
=> allow ExecReload in systemd service

conf/input.elasticsearch/elasticsearch.toml, inputs/elasticsearch/elasticsearch.go
=> fix: gather cluster info quit by err

inputs/elasticsearch/collector/cluster_settings.go, inputs/elasticsearch/collector/cluster_settings_reponse.go
=> feat: add es cluster settings metrics

inputs/snmp/table.go
https://github.com/flashcatcloud/categraf/issues/882
=> fix: snmpget continue when no such object

config/config.go, config/hostname.go
fix sn is empty && get sn fail
=> fix: fix sn is empty && get sn fail

inputs/zookeeper/zookeeper.go
fix: fix zookeeper collect blocking
tcp长连接情况下，readAll是阻塞的，如果一旦有某个zk节点发生故障，无数据返回，会导致全部zk的采集直接阻塞停止。
=> fix: fix zookeeper collect blocking

inputs/procstat/procstat.go
v0.3.60 引入的 md5Sum 在相同进程大量匹配的情况下，需要计算多次 md5，导致 Gather 性能低下
优化方案：
每轮Gather创建缓存。同一个 exe 每轮次只 md5Sum 一次。
认定为每次刮取期间内二进制不会被篡改。
Gather内无需考虑 cache 周期
适用范围：
- 同个二进制多个进程，例如 java ，php-fpm 等等
不适用于：
- 单个超大文件 md5Sum 时间长，此场景需要使用全局化的缓存，并以 (exePath, modifyTime) 作为缓存条件，并设计淘汰时间
=> perf: procstat - Cached md5 for same exe

inputs/elasticsearch/collector/indices.go, inputs/elasticsearch/collector/nodes.go, inputs/elasticsearch/collector/shards.go
1. node_stats配置了http不生效，无相关指标上报
2. 开启export_indices=true后，goroutine泄漏导致内存持续增长
=> 修复es插件相关问题

inputs/redis_sentinel/redis_sentinel.go
masterNames未赋值，master名列表为空，导致sentinel  replica和sentinels相关指标未上报
=> fix：修复sentinel指标上报缺失

agent/metrics_agent.go, conf/input.apache/apache.toml, inputs/apache/LICENSE, inputs/apache/README.md, inputs/apache/apache.go, inputs/apache/exporter/collector.go
=> feat: apache exporter

inputs/ipmi/ipmi_dash2.json
新增ipmi插件大盘，参考:https://grafana.com/grafana/dashboards/13177-ipmi-for-prometheus/
=> add new ipmi dashboard

main.go
cpu usage bug when print fail
https://github.com/flashcatcloud/categraf/issues/1143
=> fix: cpu usage rate bug when print fail

conf/input.oracle/metric.toml, conf/input.oracle/oracle.toml
=> update oracle collection configuration

conf/input.oracle/oracle.toml, inputs/oracle/oracle.go
fix: rebuild conn when oracle down
Closes #1297
=> fix: rebuild conn when oracle down

inputs/snmp/table.go
=> fix(snmp): parsePercentString func
